jumboartgallery/config/routes.rb
Artgallery::Application.routes.draw do
  resources :exhibitions

  get "tours/index"
  get "home/index"

  resources :artworks
  resources :tours

  match '/artworks/view_cat/category=:category&value=:value', :controller => 'artworks', :action => 'view_cat', :constraints => { :value => /.*/ }
  match '/artworks/getlatlng/:id' => 'artworks#get_art_latlng'
  match '/tours' => 'tours#index'
  match '/tour_items/:id' => 'tours#tour_items'
  match 'home' => redirect('/')

  root :to => "home#index"

end

jumboartgallery/app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_many :tour_items
  has_many :tour, :through => :tour_items
end

jumboartgallery/app/models/building_location.rb
class BuildingLocation < ActiveRecord::Base
end

jumboartgallery/app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
end

jumboartgallery/app/models/tour.rb
class Tour < ActiveRecord::Base
  validates_presence_of :name
  has_many :tour_items
  has_many :artwork, :through => :tour_items
end

jumboartgallery/app/models/tour_item.rb
class TourItem < ActiveRecord::Base
  belongs_to :tour
  belongs_to :artwork
end

jumboartgallery/app/models/tour_items.rb
class TourItems < ActiveRecord::Base
  belongs_to :tour
  belongs_to :artwork
end

jumboartgallery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery
  
  before_filter :prepare_for_mobile
  
  private
  
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?
  
  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end
  
end

jumboartgallery/app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  # GET /artworks
  # GET /artworks.xml
  def index
    @artworks = Artwork.all(:order => 'title ASC')
    @artists = Artwork.select("DISTINCT(creator)").order("creator ASC")
    @types = Artwork.select("DISTINCT(object)").order("object ASC")
    @locations = Artwork.select("DISTINCT(location)").order("location ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artworks }
    end
  end
  
  def view_cat
    @current_cat = "Browsing: " + params[:value]
    @artworks_by_cat = Artwork.where(params[:category] => params[:value]).all(:order => 'title ASC')
    
    respond_to do |format|
      format.html # view_cat.html.erb
    end
  end
	
  def get_art_latlng
 	 @latlng = getlatlng(params[:id])
 	 render :json => @latlng
  end	
	
  # GET /artworks/1
  # GET /artworks/1.xml
  def show
    @artwork = Artwork.find(params[:id])
	@latlng = getlatlng(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artwork }
      format.json { render :json => @latlng }
    end
  end

  # GET /artworks/new
  # GET /artworks/new.xml
  def new
    @artwork = Artwork.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artwork }
    end
  end

  # GET /artworks/1/edit
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # POST /artworks
  # POST /artworks.xml
  def create
    @artwork = Artwork.new(params[:artwork])

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully created.') }
        format.xml  { render :xml => @artwork, :status => :created, :location => @artwork }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artworks/1
  # PUT /artworks/1.xml
  def update
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      if @artwork.update_attributes(params[:artwork])
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.xml
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to(artworks_url) }
      format.xml  { head :ok }
    end
  end
  
  def getlatlng(id)

  	@last_buildings = Array.new
  	@artwork = Artwork.find(id)
  	@arr_location = @artwork.location.split(", ")[1].split(" ") # [Aidekman, Art, Center]
  	puts @arr_location
  	if not @arr_location.nil?
	  	@arr_location.each do |search_term|
  			@buildings = BuildingLocation.where("name LIKE ?", "%#{search_term}%")
  			if not @buildings.nil? and @buildings.length == 1 # There is one result.
  				return @buildings[0]
	  		elsif not @buildings.nil? and @buildings.length > 1 # There are multiple results.
  				@last_buildings = @buildings
  			elsif not @buildings.nil? and @buildings.length == 0 and @last_buildings.length > 0 #There are no new results.
  				return @last_buildings[0]
  			#elsif @buildings.nil?
  				#puts "buildings is nil"

  			end
  		end
  	end
  	#puts "ret nil"
  	return nil
  end
  
end

jumboartgallery/app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  # GET /exhibitions
  # GET /exhibitions.xml
  def index
    @exhibitions = Exhibition.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exhibitions }
    end
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.xml
  def show
    @exhibition = Exhibition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exhibition }
    end
  end

end

jumboartgallery/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@random_art = Artwork.find(:all, :offset => (Artwork.count * rand).to_i, :limit => 1)	
    respond_to do |format|
      format.html # index.html.erb
    end
  end

end

jumboartgallery/app/controllers/tours_controller.rb
class ToursController < ApplicationController
  
  def index
    @tours = Tour.all
    respond_to do |format|
    	format.html #index.mobile.erb
    end
  end

  # GET /tours/1
  # GET /tours/1.xml
  def show
    @tour = Tour.find(params[:id])
    respond_to do |format|
    	format.html #show.mobile.erb
    end
  end
  
  def tour_items
  	@tour = Tour.find(params[:id])
  	render :json => @tour.artwork
  end

end

jumboartgallery/app/helpers/application_helper.rb
module ApplicationHelper
end

jumboartgallery/app/helpers/artworks_helper.rb
module ArtworksHelper
end

jumboartgallery/app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

jumboartgallery/app/helpers/home_helper.rb
module HomeHelper
end

jumboartgallery/app/helpers/tours_helper.rb
module ToursHelper
end

jumboartgallery/app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

jumboartgallery/app/views/artworks/index.html.erb
<h1>Listing artworks</h1>

<table>
  <tr>
    <th>Object</th>
    <th>Creator</th>
    <th>Title</th>
    <th>Description</th>
    <th>Location</th>
    <th>Recfrom</th>
    <th>Date</th>
    <th>Filename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artworks.each do |artwork| %>
  <tr>
    <td><%= artwork.object %></td>
    <td><%= artwork.creator %></td>
    <td><%= artwork.title %></td>
    <td><%= artwork.description %></td>
    <td><%= artwork.location %></td>
    <td><%= artwork.recfrom %></td>
    <td><%= artwork.date %></td>
    <td><%= artwork.filename %></td>
    <td><%= link_to 'Show', artwork %></td>
    <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
    <td><%= link_to 'Destroy', artwork, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artwork', new_artwork_path %>

jumboartgallery/app/views/artworks/index.mobile.erb
<div data-role="page" id="artworks">
  
  <div data-role="header" data-theme="b" data-position="fixed">
      <h1>Browse By</h1>
      <a href="/" data-icon="home" data-back="true" class="ui-btn-right" data-iconpos="notext">Home</a>
  </div><!-- /header -->
  
  <div data-role="content">
    <ul data-role="listview">
      <li>Artist
    	<ul data-role="listview" data-filter="false">
	  <% new_header = true %>
          <% head = '~'%>
	  <% @artists.each do |artist| %>
            <%if artist.creator%>
	      <%if !head.eql?(artist.creator[0,1]) %>
	        <% head = artist.creator[0,1] %>
                <% new_header = true %>
	      <%end%>
	      <%if new_header %> 
	        <%new_header = false %>
                <li data-role="list-divider"><%=head%></li>
	      <%end%>
	      <li><a href="/artworks/view_cat/category=creator&value=<%=artist.creator%>"><%=artist.creator%></a></li>
            <%end%>
          <% end %>
        </ul>
      </li>
      <li>Title
        <ul data-role="listview" data-filter="false">
	  <% new_header = true %> 
          <% head = '~'%>
          <% @artworks.each do |artwork| %>
            <%if artwork.title%>
	      <%if !head.eql?(artwork.title[0,1]) %>
		<% head = artwork.title[0,1] %>
                <% new_header = true %>
	      <%end%>
	      <%if new_header %> 
	        <%new_header = false %>
                <li data-role="list-divider"><%=head%></li>
	      <%end%>
              <li><%= link_to artwork.title, artwork %></li>
            <%end%>
          <% end %>
        </ul>
      </li>       
      <li>Location
        <ul data-role="listview" data-filter="false">
          <% @locations.each do |location| %>
            <%if location.location%>
              <li><a href="/artworks/view_cat/category=location&value=<%=location.location%>"><%=location.location%></a></li>
            <%end%>
          <% end %>
        </ul>
      </li>
      <li>Type
        <ul data-role="listview" data-filter="false">
          <% @types.each do |type| %>
            <%if type.object%>
              <li><a href="/artworks/view_cat/category=object&value=<%=type.object%>"><%=type.object%></a></li>
            <%end%>
          <% end %>
        </ul>
      </li>
    </ul>  
  </div><!-- /content -->  
  
  <div data-role="footer" data-theme="b" data-position="fixed">
  		<div data-role="navbar">
  			<ul>
  				<li><%= link_to "Art", artworks_path, "data-icon" => "grid"  %></li>
  				<li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
  				<li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
  			</ul>
 		</div>
  </div>  <!-- /footer -->
  
</div><!-- /page -->

jumboartgallery/app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

jumboartgallery/app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Object:</b>
  <%= @artwork.object %>
</p>

<p>
  <b>Creator:</b>
  <%= @artwork.creator %>
</p>

<p>
  <b>Title:</b>
  <%= @artwork.title %>
</p>

<p>
  <b>Description:</b>
  <%= @artwork.description %>
</p>

<p>
  <b>Location:</b>
  <%= @artwork.location %>
</p>

<p>
  <b>Recfrom:</b>
  <%= @artwork.recfrom %>
</p>

<p>
  <b>Date:</b>
  <%= @artwork.date %>
</p>

<p>
  <b>Filename:</b>
  <%= @artwork.filename %>
</p>


<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
<%= link_to 'Back', artworks_path %>

jumboartgallery/app/views/artworks/show.mobile.erb

<% @image_url = "http://s3.amazonaws.com/Art_Images/#{@artwork.filename}" %>
 

<div data-role="page" id="showart">
  
  <div data-role="header" data-theme="b" data-position="fixed">
    <h1><%=@artwork.title%></h1>
      <a href="/" data-icon="home" data-back="true" class="ui-btn-right" data-iconpos="notext">Home</a>
  </div><!-- /header -->
  
  <div class="artwork-piece" data-role="content">
    <p><img src="<%= @image_url %>" HEIGHT="300" WIDTH="300"/></p>
    <p>
      <b>Object:</b>
      <a href="/artworks/view_cat/category=object&value=<%=@artwork.object%>"><%=@artwork.object%></a>
    </p>

    <p>
      <b>Creator:</b>
      <a href="/artworks/view_cat/category=creator&value=<%=@artwork.creator%>"><%=@artwork.creator%></a>
    </p>

    <p>
      <b>Title:</b>
      <%= @artwork.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @artwork.description %>
    </p>

    <p>
      <b>Location:</b>
      <a href="/artworks/view_cat/category=location&value=<%=@artwork.location%>"><%=@artwork.location%></a>
    </p>

    <p>
      <b>Recfrom:</b>
      <%= @artwork.recfrom %>
    </p>

    <p>
      <b>Date:</b>
      <%= @artwork.date %>
    </p>

	<p>
		<b>Expected here: LatLng info</b>
		<% if @latlng.nil? %>
		nil :(
		<% else %>
		<%= @latlng.name %>: (<%= @latlng.lat %>,<%= @latlng.lng %>) 
		<% end %>
	</p>

    <p>
      <b>Filename:</b>
      <%= @artwork.filename %>
    </p>   
  </div><!-- /content -->
  
  <div data-role="footer" data-theme="b" data-position="fixed">
  		<div data-role="navbar">
  			<ul>
  				<li><%= link_to "Art", artworks_path, "data-icon" => "grid"  %></li>
  				<li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
  				<li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
  			</ul>
 		</div>
  </div> <!-- /footer -->
   
</div><!-- /page -->

jumboartgallery/app/views/artworks/view_cat.mobile.erb
<div data-role="page" id="artworks_by_cat">
  
  <div data-role="header" data-theme="b" data-position="fixed">
    <h1><%=@current_cat%></h1>
      <a href="/" data-icon="home" data-back="true" class="ui-btn-right" data-iconpos="notext">Home</a>
  </div><!-- /header -->
  
  <div data-role="content">    
    <ul data-role="listview" data-filter="false" data-position="fixed">
      <% @artworks_by_cat.each do |artwork| %>
        <li><%= link_to artwork.title, artwork %></li>
      <% end %>
    </ul>        
  </div><!-- /content -->  
  
    <div data-role="footer" data-theme="b" data-position="fixed">
  		<div data-role="navbar">
  			<ul>
  				<li><%= link_to "Art", artworks_path, "data-icon" => "grid"  %></li>
  				<li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
  				<li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
  			</ul>
 		</div>
  </div><!-- /footer -->  
   
</div><!-- /page -->

jumboartgallery/app/views/exhibitions/edit.html.erb
<h1>Editing exhibition</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

jumboartgallery/app/views/exhibitions/index.html.erb
<h1>Listing exhibitions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Open</th>
    <th>Close</th>
    <th>Description</th>
    <th>Location</th>
    <th>Image1</th>
    <th>Image2</th>
    <th>Image3</th>
    <th>Image4</th>
    <th>Image5</th>
    <th>Opening</th>
    <th>Filename</th>
    <th>Opening end</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exhibitions.each do |exhibition| %>
  <tr>
    <td><%= exhibition.name %></td>
    <td><%= exhibition.open %></td>
    <td><%= exhibition.close %></td>
    <td><%= exhibition.description %></td>
    <td><%= exhibition.location %></td>
    <td><%= exhibition.image1 %></td>
    <td><%= exhibition.image2 %></td>
    <td><%= exhibition.image3 %></td>
    <td><%= exhibition.image4 %></td>
    <td><%= exhibition.image5 %></td>
    <td><%= exhibition.opening %></td>
    <td><%= exhibition.filename %></td>
    <td><%= exhibition.opening_end %></td>
    <td><%= link_to 'Show', exhibition %></td>
    <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
    <td><%= link_to 'Destroy', exhibition, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exhibition', new_exhibition_path %>

jumboartgallery/app/views/exhibitions/index.mobile.erb
<div data-role="page" id="exhibitions">
  <div data-role="header" data-theme="b" data-position="fixed">
      <h1>Browse Exhibitions</h1>
      <a href="/" data-icon="home" data-back="true" class="ui-btn-right" data-iconpos="notext">Home</a>
  </div><!-- /header -->
  <div data-role="content">
    <ul data-role="listview">
      <% @exhibitions.each do |exhibition| %>
      <li>
        <%= link_to exhibition.name, exhibition %>
      </li>
      <% end %>
    </ul>
  </div>
  <div data-role="footer" data-theme="b" data-position="fixed">
                <div data-role="navbar">
                        <ul>
                                <li><%= link_to "Art", artworks_path, "data-icon" => "grid"  %></li>
                                <li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
                                <li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
                        </ul>
                </div>
  </div>  <!-- /footer -->

</div>

jumboartgallery/app/views/exhibitions/new.html.erb
<h1>New exhibition</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibitions_path %>

jumboartgallery/app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @exhibition.name %>
</p>

<p>
  <b>Open:</b>
  <%= @exhibition.open %>
</p>

<p>
  <b>Close:</b>
  <%= @exhibition.close %>
</p>

<p>
  <b>Description:</b>
  <%= @exhibition.description %>
</p>

<p>
  <b>Location:</b>
  <%= @exhibition.location %>
</p>

<p>
  <b>Image1:</b>
  <%= @exhibition.image1 %>
</p>

<p>
  <b>Image2:</b>
  <%= @exhibition.image2 %>
</p>

<p>
  <b>Image3:</b>
  <%= @exhibition.image3 %>
</p>

<p>
  <b>Image4:</b>
  <%= @exhibition.image4 %>
</p>

<p>
  <b>Image5:</b>
  <%= @exhibition.image5 %>
</p>

<p>
  <b>Opening:</b>
  <%= @exhibition.opening %>
</p>

<p>
  <b>Filename:</b>
  <%= @exhibition.filename %>
</p>

<p>
  <b>Opening end:</b>
  <%= @exhibition.opening_end %>
</p>


<%= link_to 'Edit', edit_exhibition_path(@exhibition) %> |
<%= link_to 'Back', exhibitions_path %>

jumboartgallery/app/views/exhibitions/show.mobile.erb
<div data-role="page" id="showexhibition">
  <div data-role="header" data-theme="b" data-position="fixed">
    <h1>Exhibition Detail</h1>
      <a href="/" data-icon="home" data-back="true" class="ui-btn-right" data-iconpos="notext">Home</a>
  </div><!-- /header -->

  <div class="exhibition" data-role="content">
    <p>
      <b>Name:</b>
      <%= @exhibition.name %>
    </p>
    
    <p>
      <b>Open:</b>
      <%= @exhibition.open %>
    </p>
    
    <p>
      <b>Close:</b>
      <%= @exhibition.close %>
    </p>
    
    <p>
      <b>Description:</b>
      <%= @exhibition.description %>
    </p>
    
    <p>
      <b>Location:</b>
      <%= @exhibition.location %>
    </p>
    
    <p>
      <b>Image1:</b>
      <%= @exhibition.image1 %>
    </p>
    
    <p>
      <b>Image2:</b>
      <%= @exhibition.image2 %>
    </p>
    
    <p>
      <b>Image3:</b>
      <%= @exhibition.image3 %>
    </p>
    
    <p>
      <b>Image4:</b>
      <%= @exhibition.image4 %>
    </p>
    
    <p>
      <b>Image5:</b>
      <%= @exhibition.image5 %>
    </p>
    
    <p>
      <b>Opening:</b>
      <%= @exhibition.opening %>
    </p>
    
    <p>
      <b>Filename:</b>
      <%= @exhibition.filename %>
    </p>
  </div><!-- /content -->

  <div data-role="footer" data-theme="b" data-position="fixed">
                <div data-role="navbar">
                        <ul>
                                <li><%= link_to "Art", artworks_path, "data-icon" => "grid"  %></li>
                                <li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
                                <li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
                        </ul>
                </div>
  </div> <!-- /footer -->
</div><!--/page -->

jumboartgallery/app/views/home/index.html.erb
<h1>This is the homepage</h1>
<p>Click <%= link_to "Here", artworks_path %> to see a list of all the artwork in the DB</p>

jumboartgallery/app/views/home/index.mobile.erb
<style type="text/css">
.active {
    display:inherit;
}

.inactive {
    display:none;    
}
</style>
<div data-role="page" id="home">
  
  <div data-role="header" data-theme="b" data-backbtn="false">
    <h1><%= image_tag "tuagbanner.jpg" %></h1>
  </div><!-- /header -->
  
  <div data-role="content">
  	<div id="img_rotator" style="text-align:center;">
  		<% @random_art.each do |art| %>
  		  <div>
  		    <a href="<%= url_for(art) %>"> 
      			<img src="http://s3.amazonaws.com/Art_Images/<%= art.filename %>" HEIGHT="200" WIDTH="200"/>
      			<p><%= art.title %></p>
  	    	</a>
        </div>
  		<% end %> 		
  	</div><!-- /img rotator -->
  	
    <ul data-role="listview" data-inset="true">
      <li><%= link_to content_tag(:h1, "Art Collection") + content_tag(:p, "Checkout the Tufts University Art Collection!"), artworks_path %><p></p></li>
      <li><%= link_to content_tag(:h1, "Exhibitions") + content_tag(:p, "Browse our Exhibitions"), exhibitions_path %><p></p></li>
      <li><h1>Information</h1><p>Hours, contact info, and more information regarding the Tufts Art Gallery</p></li>
      <li><%= link_to content_tag(:h1, "Tours") + content_tag(:p, "Browse our virtual Mobile Tours!"), tours_path %></li>
    </ul>
  </div><!-- /content -->
  
    <div data-role="footer" data-theme="b" data-position="fixed">
  		<div data-role="navbar">
  			<ul>
  				<li><%= link_to "Art", artworks_path, "data-icon" => "grid" %></li>
  				<li><a href="/info" data-icon="info">Info</a></li>
  				<li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
  			</ul>
 		</div>
  </div><!-- /footer -->
  
</div><!-- /page -->
<script type="text/javascript">
    $('#img_rotator div').addClass('inactive');
    $('#img_rotator div:first').addClass('active').removeClass('inactive');
  function slideSwitch() {
    var $active = $('#img_rotator div.active');
    if ($active.length == 0) $active = $('#img_rotator div:last');
    var $next = $active.next().length ? $active.next() : $('#img_rotator div:first');
    $next.addClass('active').removeClass('inactive');
    $active.removeClass('active').addClass('inactive');
  }
  setInterval("slideSwitch()", 5000);
</script>

jumboartgallery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artgallery</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'mobile' if mobile_device? %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <% if mobile_device? %>
    <%= link_to "Full Site", :mobile => 0 %>
  <% else %>
    <%= link_to "Mobile Site", :mobile => 1 %>
  <% end %>
  
  <%= yield %>

</body>
</html>

jumboartgallery/app/views/tours/index.mobile.erb
<div data-role="page" id="tours">
  
  <div data-role="header" data-theme="b" data-position="fixed">
    <h1>Mobile Tours</h1>
    <%= link_to "", {:controller => "home", :action => "index"}, :class => "ui-btn-right", "data-icon" => "home", "data-iconpos" => "notext"  %>
  </div><!-- /header -->
  
  <div data-role="content">
	
	<ul data-role="listview" data-inset="true">
		<% @tours.each do |tour| %>
		<li>
			<a href="<%= url_for(tour) %>" data-ajax="false">
			<h1><%= tour.name %></h1>
			<p><%= tour.desc %></p>
			</a>
		</li>
		<% end %>
	</ul>
		
  </div><!-- /content -->
  
    <div data-role="footer" data-theme="b" data-position="fixed">
  		<div data-role="navbar">
  			<ul>
  				<li><%= link_to "Art", artworks_path, "data-icon" => "grid" %></li>
  				<li><%= link_to "Home", {:controller => "home", :action => "index"}, "data-icon" => "home" %></li>
  				<li><%= link_to "Tours", tours_path, "data-icon" => "star" %></li>
  			</ul>
 		</div>
  </div><!-- /footer -->
  
</div><!-- /page -->

jumboartgallery/app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Displaying Tour: "<%= @tour.name %>"</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th>Location</th>
	<th>Photo</th>
  </tr>


<% @tour.artwork.each do |art| %>
  <tr class="item" title="<%= art.description %>">
    <td><%= art.title %></td>
    <td><%= art.creator %></td>
    <td><%= art.location %></td>
	<td>
		<img src="http://s3.amazonaws.com/Art_Images/<% art.filename %>" />
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tour', new_tour_path %>
<style type="text/css">
  div#navbar a:nth-child(4){
    background-color:#CEF6F5;
}
</style>


<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>
<style type="text/css">
  div#navbar a:nth-child(5){
    background-color:#CEF6F5;
}
</style>